<?php

namespace Athphane\ProgrammerQuotes;


use Illuminate\Support\Collection;

class ProgrammerQuotes
{
    public static function random()
    {
        return Collection::make([
            "The separation of architectural effort from implementation is a very powerful way of getting conceptual integrity on very large projects. - Fred Brooks",
            "Any intelligent fool can make things bigger, more complex, and more violent. It takes a touch of genius – and a lot of courage – to move in the opposite direction. - Albert Einstein",
            "Thus it is observable that the buildings which a single architect has planned and executed, are generally more elegant and commodious than those which several have attempted to improve. - René Descartes",
            "The first false assumption that underlies the scheduling of systems programming is that all will go well, i.e., that each task will hike only as long as it \"ought\" to take. A large programming effort, however, consists of many tasks, some chained end-to-end. The probability that each will go well becomes vanishingly small. - Fred Brooks",
            "For all its power, the computer is a harsh taskmaster. Its programs must be correct, and what we wish to say must be said accurately in every detail. - Alan Perlis",
            "I'm doing a free operating system (just a hobby, won't be big and professional like GNU). - Linus Torvalds",
            "Debugging time increases as a square of the program’s size. - Chris Wenham",
            "Mathematics is important in programming, but it’s just one of a lot of things that are important. If you overemphasize the math then you underemphasize stuff which might be even more important, such as literacy. - Douglas Crockford",
            "Right now you are a prisoner of each application you use. You have only the options that were given you by the developer of that application. - Ted Nelson",
            "Two centuries ago Leibnitz invented a calculating machine which embodied most of the essential features of recent keyboard devices, but it could not then come into use. The economics of the situation were against it. - Vannevar Bush",
            "Every program has (at least) two purposes: the one for which it was written and another for which it wasn't. - Alan Perlis",
            "If each part of the task must be separately coordinated with each other part, the effort increases as n(n-1)/2. Three workers require three times as much pairwise intercommunication as two; four require six times as much as two. - Fred Brooks",
            "Part of what makes programming difficult is most of the time we’re doing stuff we’ve never done before. - Douglas Crockford",
            "Make a guess, double the number, and then move to the next larger unit of time. This rule scales tasks in a very interesting way: a one-minute task explodes by a factor of 120 to take two hours. A one-hour job explodes by \"only\" a factor 48 to take two days, while a one-day job grows by a factor of 14 to take two weeks. - Poul-Henning Kamp",
            "Most errors are introduced during requirements specification! - Daniel T. Barry",
            "It is practically impossible to teach good programming to students that have had a prior exposure to BASIC: as potential programmers they are mentally mutilated beyond hope of regeneration. - Edsger W. Dijkstra",
            "Cool URIs don't change. - Tim Berners-Lee",
            "I think there is a world market for maybe five computers. - Thomas J. Watson",
            "The most important single aspect of software development is to be clear about what you are trying to build. - Bjarne Stroustrup",
            "Imagination is more important than knowledge. - Albert Einstein",
            "I never in my wildest dreams would have predicted the evolution of the Internet. And I never would’ve predicted the degree to which corporate influence over the Internet has changed its character over time. - L. Peter Deutsch",
            "I have yet to see any problem, however complicated, which when looked at in the right way, did not become more complicated. - Poul Anderson",
            "People under pressure don’t work better; they just work faster. - Tom DeMarco",
            "A program that produces incorrect results twice as fast is infinitely slower. - John Ousterhout",
            "If you give someone a program, you will frustrate them for a day; if you teach them how to program, you will frustrate them for a lifetime. - David Leinweber",
            "C is quirky, flawed, and an enormous success. - Dennis Ritchie",
            "In order to understand recursion, one must first understand recursion. - Anonymous",
            "The most powerful programming language is Lisp. If you don't know Lisp (or its variant, Scheme), you don't know what it means for a programming language to be powerful and elegant. Once you learn Lisp, you will understand what is lacking in most other languages. - Richard Stallman",
            "The most effective debugging tool is still careful thought, coupled with judiciously placed print statements. - Brian Kernighan",
            "Flaws in computer programs are usually called bugs. It makes programmers feel good to imagine them as little things that just happen to crawl into our work. In reality, of course, we put them there ourselves. - Marijn Haverbeke",
            "You should name a variable using the same care with which you name a first-born child. - Jim Coplien",
            "What is simplicity? Simplicity is the shortest path to a solution. - Ward Cunningham",
            "A programming systems product takes about nine times as much effort as the component programs written separately for private use. - Fred Brooks",
            "Life is too short to run proprietary software. - Bdale Garbee",
            "I just had to take the hypertext idea and connect it to the TCP and DNS ideas and — ta-da!— the World Wide Web. - Tim Berners-Lee",
            "Documenting is very, very hard; it’s time-consuming. To do it right, you’ve got to do it like programming. You’ve got to deconstruct it, put it together in nice ways, rewrite it when it’s wrong. People don’t do that. - Ken Thompson",
            "We build our computer systems the way we build our cities: over time, without a plan, on top of ruins. - Ellen Ullman",
            "The use of COBOL cripples the mind; its teaching should, therefore, be regarded as a criminal offense. - Edsger W. Dijkstra",
            "I invented the Web just because I needed it, really, because it was so frustrating that it didn't exit. - Tim Berners-Lee",
            "I have no special talent. I am only passionately curious. - Albert Einstein",
            "If you need more than 3 levels of indentation, you're screwed anyway, and should fix your program. - Linus Torvalds",
            "The science of operations, as derived from mathematics more especially, is a science of itself, and has its own abstract truth and value. - Ada Lovelace",
            "Programming is similar to a game of golf. The point is not getting the ball in the hole but how many strokes it takes. - Harlan Mills",
            "There is never enough time to do it right, but there is always enough time to fix it or to do it over. - Daniel T. Barry",
            "Software is usually expected to be modified over the course of its productive life. The process of converting one correct program into a different correct program is extremely challenging. - Douglas Crockford",
            "I make mistakes because I’m always operating at my limit. If I only stay in comfortable territory all the time, that’s not so much fun. - Donald Knuth",
            "Sometimes there is a silver bullet for boosting software engineering productivity. But you need to shoot the right person. - Michael Stal",
            "The cost to repair an error goes up dramatically as project moves towards completion and beyond. - Daniel T. Barry",
            "Very good professional programmers are ten times as productive as poor ones, at same training and two-year experience level. - Fred Brooks",
            "With testing, I know straight away when I added a bug. That lets me fix the bug immediately, before it can crawl off and hide. - Martin Fowler",
            "Ed Adams of IBM found that 80% of the reliability problems are caused by only 2% of the defects. - Daniel T. Barry",
            "While much attention has been focused on high-level software architectural patterns, what is, in effect, the de-facto standard software architecture is seldom discussed: the Big Ball of Mud. - Joseph Yoder (computer scientist)",
            "The code you write makes you a programmer. The code you delete makes you a good one. The code you don't have to write makes you a great one. - Mario Fusco",
            "The top 5% of programmers probably write 99% of the good software. - Paul Graham (programmer)",
            "If you think your users are idiots, only idiots will use it. - Linus Torvalds",
            "The acts of the mind, wherein it exerts its power over simple ideas, are chiefly these three: 1. Combining several simple ideas into one compound one, and thus all complex ideas are made. 2. The second is bringing two ideas, whether simple or complex, together, and setting them by one another so as to take a view of them at once, without uniting them into one, by which it gets all its ideas of relations. 3. The third is separating them from all other ideas that accompany them in their real existence: this is called abstraction, and thus all its general ideas are made. - John Locke",
            "One of the things I’ve been pushing is code reading. I think that is the most useful thing that a community of programmers can do for each other—spend time on a regular basis reading each other’s code. - Douglas Crockford",
            "Every good work of software starts by scratching a developer’s personal itch. - Eric S. Raymond",
            "It's fun to sit at a terminal and let the code flow. It sounds strange, but it just comes out my brain; once I'm started, I don't have to think about it. - Gary Kildall",
            "I'm convinced that about half of what separates the successful entrepreneurs from the non-successful ones is pure perseverance. It is so hard. - Steve Jobs",
            "There is no reason anyone would want a computer in their home. - Ken Olsen",
            "JavaScript, purely by accident, has become the most popular programming language in the world. - Douglas Crockford",
            "I consider that the golden rule requires that if I like a program I must share it with other people who like it. Software sellers want to divide the users and conquer them, making each user agree not to share with others. I refuse to break solidarity with other users in this way. - Richard Stallman",
            "The purpose of software engineering is to control complexity, not to create it. - Pamela Zave",
            "I always spend a day a week learning new stuff. That means I spend 20% more of my time than my colleagues learning new stuff. Now 20% at compound interest means that after four and a half years I will know twice as much as them. - Richard Hamming",
            "If builders built houses the way programmers built programs, the first woodpecker to come along would destroy civilization. - Gerald Weinberg",
            "When I am working on a problem I never think about beauty. I think only how to solve the problem. But when I have finished, if the solution is not beautiful, I know it is wrong. - Buckminster Fuller",
            "There certainly will be job disruption. Because what's going to happen is robots will be able to do everything better than us. - Elon Musk",
            "In science if you know what you are doing you should not be doing it. In engineering if you do not know what you are doing you should not be doing it. - Richard Hamming",
            "Before software can be reusable it first has to be usable. - Ralph Johnson (computer scientist)",
            "Simplicity and elegance are unpopular because they require hard work and discipline to achieve and education to be appreciated. - Edsger W. Dijkstra",
            "I invented the term 'Object-Oriented', and I can tell you I did not have C++ in mind. - Alan Kay",
            "The trouble with programmers is that you can never tell what a programmer is doing until it’s too late. - Seymour Cray",
            "No code is faster than no code. - Kevlin Henney",
            "The amateur software engineer is always in search of magic, some sensational method or tool whose application promises to render software development trivial. It is the mark of the professional software engineer to know that no such panacea exist. - Grady Booch",
            "There are few sources of energy so powerful as a procrastinating grad student. - Paul Graham (programmer)",
            "In 1971 when I joined the staff of the MIT Artificial Intelligence lab, all of us who helped develop the operating system software, we called ourselves hackers. We were not breaking any laws, at least not in doing the hacking we were paid to do. We were developing software and we were having fun. Hacking refers to the spirit of fun in which we were developing software. - Richard Stallman",
            "A distributed system is one in which the failure of a computer you didn’t even know existed can render your own computer unusable. - Leslie Lamport",
            "There are many terrible mistakes to make in program design, so go ahead and make them so that you understand them better. - Marijn Haverbeke",
            "Don’t go into a two-year development with nothing coming out in the middle. Have something come out every two months, so you can evaluate, regroup, and restart. - John Warnock",
            "There are only two kinds of languages: the ones people complain about and the ones nobody uses. - Bjarne Stroustrup",
            "Ideas don't disappear. They change form, they merge with other ideas. - Bob Frankston",
            "Reliable computations are obtainable from buggy programs, which after all, are the only kind of programs there are. - Daniel T. Barry",
            "Never memorize something that you can look up. - Albert Einstein",
            "Most programming languages contain good parts and bad parts. I discovered that I could be better programmer by using only the good parts and avoiding the bad parts. - Douglas Crockford",
            "When I was at what I would consider the peak of my abilities, I had extremely trustworthy intuition. I would do things and they would just turn out right. - L. Peter Deutsch",
            "No matter how correct a mathematical theorem may appear to be, one ought never to be satisfied that there was not something imperfect about it until it also gives the impression of being beautiful. - George Boole",
            "From an artistic standpoint, the best software comes from the realm of intuition. - Bob Carr",
            "Any one who considers arithmetical methods of producing random digits is, of course, in a state of sin. For, as has been pointed out several times, there is no such thing as a random number. - John von Neumann",
            "Debugging is like being the detective in a crime movie where you are also the murderer. - Filipe Fortes",
            "In theory, there is no difference between theory and practice. But, in practice, there is. - Jan L. A. van de Snepscheut",
            "Thoroughly testing a program is impossible (requires unbounded number of test cases); so try to choose test cases that will expose all errors. That’s very difficult, especially since we do not know what all the errors are, and if we did, we would not need the test cases! - Daniel T. Barry",
            "Reviews and pair programming provide programmers with something their work would not otherwise have: an audience. Sunlight, it is said is a powerful disinfectant. An immediate audience of one's peers provides immediate incentives to programmers to keep their code clear and comprehensible, as well as functional. - Joseph Yoder (computer scientist)",
            "I’ve never been a lover of existing code. Code by itself almost rots and it’s gotta be rewritten. Even when nothing has changed, for some reason it rots. - Ken Thompson",
            "JavaScript is the world's most misunderstood programming language. - Douglas Crockford",
            "When I invented the web, I didn't have to ask anyone's permission. - Tim Berners-Lee",
            "The cost of adding a feature isn’t just the time it takes to code it. The cost also includes the addition of an obstacle to future expansion. The trick is to pick the features that don’t fight each other. - John Carmack",
            "Science is what we understand well enough to explain to a computer. Art is everything else we do. - Donald Knuth",
            "Everything should be made as simple as possible. But to do that you have to master complexity. - Butler Lampson",
            "The way to arrest entropy in software is to refactor it. - Joseph Yoder (computer scientist)",
            "You can’t trust code that you did not totally create yourself. - Ken Thompson",
            "The difference between theory and practice is that in theory, there is no difference between theory and practice. - Richard Moore (engineer)",
            "When in doubt, leave it out. - Joshua Bloch",
            "Humanity is acquiring all the right technology for all the wrong reasons. - Buckminster Fuller",
            "By June 1949 people had begun to realize that it was not so easy to get programs right as at one time appeared. - Maurice Wilkes",
            "Computers themselves can do only stupidly straightforward things. The reason they are so useful is that they do these things at an incredibly high speed. - Marijn Haverbeke",
            "It’s all talk until the code runs. - Ward Cunningham",
            "Everybody should learn to program a computer, because it teaches you how to think. - Steve Jobs",
            "To be successful, you want to surround yourself with very talented folks whose skills blend very well. That’s the secret of success. - John Warnock",
            "Good people with a good process will outperform good people with no process every time. - Grady Booch",
            "Educators, generals, dieticians, psychologists, and parents program. Armies, students, and some societies are programmed. - Alan Perlis",
            "There's nothing more permanent than a temporary hack. - Kyle Simpson",
            "In the case of the Analytical Engine, we have undoubtedly to lay out a certain capital of analytical labour in one particular line, but this is in order that the engine may bring us in a much larger return in another line. - Ada Lovelace",
            "A display connected to a digital computer gives us a chance to gain familiarity with concepts not realizable in the physical world. It is a looking glass into a mathematical wonderland. - Ivan Sutherland",
            "I’ll use dirty tricks for two reasons. One is, if it’s really going to give me a performance improvement. Or sometimes just for pure pleasure. In any case, I document it; I don’t just put it in there. - Donald Knuth",
            "Maintenance cost is strongly affected by the number of users. More users find more bugs. - Fred Brooks",
            "The fundamental problem with program maintenance is that fixing a defect has a substantial (20-50 percent) chance of introducing another. So the whole process is two steps forward and one step back. - Fred Brooks",
            "Within a computer, natural language is unnatural. - Alan Perlis",
            "False scheduling to match the patron's desired date is much more common in our discipline than elsewhere in engineering. - Fred Brooks",
            "Software gets slower faster than hardware gets faster. - Niklaus Wirth",
            "The act of describing a program in unambiguous detail and the act of programming are one and the same. - Kevlin Henney",
            "Programming is a little bit like the army. Now that I'm out, it's neat to have had the experience. - Wayne Ratliff",
            "I think the best way to make JavaScript better would be to make it smaller. If we could just get it down to what it does really well and remove the features that add little or no value, it’s actually a better language. - Douglas Crockford",
            "The class of problems that are computable by a digital computer apparently includes every problem that is computable by any kind of device. - Danny Hillis",
            "The problem with object-oriented languages is they’ve got all this implicit environment that they carry around with them. You wanted a banana but what you got was a gorilla holding the banana and the entire jungle. - Joe Armstrong (programmer)",
            "The free software community rejects the “priesthood of technology”, which keeps the general public in ignorance of how technology works; we encourage students of any age and situation to read the source code and learn as much as they want to know. - Richard Stallman",
            "Should array indices start at 0 or 1? My compromise of 0.5 was rejected without, I thought, proper consideration. - Stan Kelly-Bootle",
            "To achieve conceptual integrity, a design must proceed from one mind or a small group of agreeing minds. - Fred Brooks",
            "Is studying computer science the best way to prepare to be a programmer? No. the best way to prepare is to write programs, and to study great programs that other people have written. - Bill Gates",
            "What we wanted to preserve was not just a good environment in which to do programming, but a system around which fellowship could form. - Dennis Ritchie",
            "The path to the CEO's office should not be through the CFO's office, and it should not be through the marketing department. It needs to be through engineering and design. - Elon Musk",
            "Don't worry about anything. Just do what you can and be the best you can be. - Douglas Crockford",
            "If you can get today’s work done today, but you do it in such a way that you can’t possibly get tomorrow’s work done tomorrow, then you lose. - Martin Fowler",
            "I think of myself as a writer. Sometimes I write in English and sometimes I write in JavaScript. - Douglas Crockford",
            "On two occasions I have been asked [by members of Parliament]: \"Pray, Mr . Babbage, if you put into the machine wrong figures, will the right answers come out ? \" I am not able rightly to apprehend the kind of confusion of ideas that could provoke such a question. - Charles Babbage",
            "Like a financial debt, the technical debt incurs interest payments, which come in the form of the extra effort that we have to do in future development because of the quick and dirty design choice. - Martin Fowler",
            "Young man, in mathematics you don't understand things. You just get used to them. - John von Neumann",
            "Really good programs live forever. - Charles Simonyi",
            "Beware of bugs in the above code; I have only proved it correct, not tried it. - Donald Knuth",
            "We have already mentioned what may, perhaps, appear paradoxical to some of our readers, — that the division of labour can be applied with equal success to mental as to mechanical operations, and that it ensures in both the same economy of time. - Charles Babbage",
            "A team of highly competent programmers who are also highly territorial, egotistical politicians will fail while a team of equally competent programmers, who are also egoless, cooperative, team players will succeed. - Daniel T. Barry",
            "A complex system that works is invariably found to have evolved from a simple system that worked. The inverse proposition also appears to be true: A complex system designed from scratch never works and cannot be made to work. - John Gall (author)",
            "The programs we use to conjure processes are like a sorcerer's spells. They are carefully composed from symbolic expressions in arcane and esoteric programming languages that prescribe the tasks we want our processes to perform. - Hal Abelson",
            "An interactive debugger is an outstanding example of what is not needed - it encourages trial-and-error hacking rather than systematic design, and also hides marginal people barely qualified for precision programming. - Harlan Mills",
            "A computer shall not waste your time or require you to do more work than is strictly necessary. - Jef Raskin",
            "A program is a building of thought. It is costless to build, it is weightless, and it grows easily under our typing hands. But without care, a program’s size and complexity will grow out of control, confusing even the person who created it. - Marijn Haverbeke",
            "The only way to learn a new programming language is by writing programs in it. - Dennis Ritchie",
            "I will, in fact, claim that the difference between a bad programmer and a good one is whether he considers his code or his data structures more important. Bad programmers worry about the code. Good programmers worry about data structures and their relationships. - Linus Torvalds",
            "Computer science education cannot make anybody an expert programmer any more than studying brushes and pigment can make somebody an expert painter. - Eric S. Raymond",
            "If you think it's simple, then you have misunderstood the problem. - Bjarne Stroustrup",
            "Whenever logical processes of thought are employed, there is an opportunity for the machine. - Vannevar Bush",
            "Every time you improve process, work becomes harder. - Daniel T. Barry",
            "I think the best way to supervise is by personal example and by frequent code reviews. - Charles Simonyi",
            "Mathematicians stand on each others' shoulders and computer scientists stand on each others' toes. - Richard Hamming",
            "Beauty is more important in computing than anywhere else in technology because software is so complicated. Beauty is the ultimate defense against complexity. - David Gelernter",
            "The entire history of software engineering is that of the rise in levels of abstraction. - Grady Booch",
            "The programmer, like the poet, works only slightly removed from pure thought-stuff. He builds his castles in the air, from air, creating by exertion of the imagination. Few media of creation are so flexible, so easy to polish and rework, so readily capable of realizing grand conceptual structures. - Fred Brooks",
            "The competent programmer is fully aware of the strictly limited size of his own skull; therefore he approaches the programming task in full humility, and among other things he avoids clever tricks like the plague - Edsger W. Dijkstra",
        ])->random();
    }
}
